# Generated by Django 6.0.3 on 2026-03-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_alter_rendezvous_medecin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together={('medecin', 'date', 'heure')},
        ),
    ]
